# Yet another libui-ng wrapper for Ruby
#
# * https://github.com/vaiorabbit/libuing-bindings
#
# [NOTICE] Autogenerated. Do not edit.

require 'ffi'

module UI

  extend FFI::Library

  # Define/Macro

  Pi = 3.14159265358979323846264338327950288419716939937510582097494459
  DrawDefaultMiterLimit = 10.0
  TableModelColumnNeverEditable = -1
  TableModelColumnAlwaysEditable = -2

  # Enum

  ForEachContinue = 0
  ForEachStop = 1
  WindowResizeEdgeLeft = 0
  WindowResizeEdgeTop = 1
  WindowResizeEdgeRight = 2
  WindowResizeEdgeBottom = 3
  WindowResizeEdgeTopLeft = 4
  WindowResizeEdgeTopRight = 5
  WindowResizeEdgeBottomLeft = 6
  WindowResizeEdgeBottomRight = 7
  DrawBrushTypeSolid = 0
  DrawBrushTypeLinearGradient = 1
  DrawBrushTypeRadialGradient = 2
  DrawBrushTypeImage = 3
  DrawLineCapFlat = 0
  DrawLineCapRound = 1
  DrawLineCapSquare = 2
  DrawLineJoinMiter = 0
  DrawLineJoinRound = 1
  DrawLineJoinBevel = 2
  DrawFillModeWinding = 0
  DrawFillModeAlternate = 1
  AttributeTypeFamily = 0
  AttributeTypeSize = 1
  AttributeTypeWeight = 2
  AttributeTypeItalic = 3
  AttributeTypeStretch = 4
  AttributeTypeColor = 5
  AttributeTypeBackground = 6
  AttributeTypeUnderline = 7
  AttributeTypeUnderlineColor = 8
  AttributeTypeFeatures = 9
  TextWeightMinimum = 0
  TextWeightThin = 100
  TextWeightUltraLight = 200
  TextWeightLight = 300
  TextWeightBook = 350
  TextWeightNormal = 400
  TextWeightMedium = 500
  TextWeightSemiBold = 600
  TextWeightBold = 700
  TextWeightUltraBold = 800
  TextWeightHeavy = 900
  TextWeightUltraHeavy = 950
  TextWeightMaximum = 1000
  TextItalicNormal = 0
  TextItalicOblique = 1
  TextItalicItalic = 2
  TextStretchUltraCondensed = 0
  TextStretchExtraCondensed = 1
  TextStretchCondensed = 2
  TextStretchSemiCondensed = 3
  TextStretchNormal = 4
  TextStretchSemiExpanded = 5
  TextStretchExpanded = 6
  TextStretchExtraExpanded = 7
  TextStretchUltraExpanded = 8
  UnderlineNone = 0
  UnderlineSingle = 1
  UnderlineDouble = 2
  UnderlineSuggestion = 3
  UnderlineColorCustom = 0
  UnderlineColorSpelling = 1
  UnderlineColorGrammar = 2
  UnderlineColorAuxiliary = 3
  DrawTextAlignLeft = 0
  DrawTextAlignCenter = 1
  DrawTextAlignRight = 2
  ModifierCtrl = 1
  ModifierAlt = 2
  ModifierShift = 4
  ModifierSuper = 8
  ExtKeyEscape = 1
  ExtKeyInsert = 2
  ExtKeyDelete = 3
  ExtKeyHome = 4
  ExtKeyEnd = 5
  ExtKeyPageUp = 6
  ExtKeyPageDown = 7
  ExtKeyUp = 8
  ExtKeyDown = 9
  ExtKeyLeft = 10
  ExtKeyRight = 11
  ExtKeyF1 = 12
  ExtKeyF2 = 13
  ExtKeyF3 = 14
  ExtKeyF4 = 15
  ExtKeyF5 = 16
  ExtKeyF6 = 17
  ExtKeyF7 = 18
  ExtKeyF8 = 19
  ExtKeyF9 = 20
  ExtKeyF10 = 21
  ExtKeyF11 = 22
  ExtKeyF12 = 23
  ExtKeyN0 = 24
  ExtKeyN1 = 25
  ExtKeyN2 = 26
  ExtKeyN3 = 27
  ExtKeyN4 = 28
  ExtKeyN5 = 29
  ExtKeyN6 = 30
  ExtKeyN7 = 31
  ExtKeyN8 = 32
  ExtKeyN9 = 33
  ExtKeyNDot = 34
  ExtKeyNEnter = 35
  ExtKeyNAdd = 36
  ExtKeyNSubtract = 37
  ExtKeyNMultiply = 38
  ExtKeyNDivide = 39
  AlignFill = 0
  AlignStart = 1
  AlignCenter = 2
  AlignEnd = 3
  AtLeading = 0
  AtTop = 1
  AtTrailing = 2
  AtBottom = 3
  TableValueTypeString = 0
  TableValueTypeImage = 1
  TableValueTypeInt = 2
  TableValueTypeColor = 3
  SortIndicatorNone = 0
  SortIndicatorAscending = 1
  SortIndicatorDescending = 2
  TableSelectionModeNone = 0
  TableSelectionModeZeroOrOne = 1
  TableSelectionModeOne = 2
  TableSelectionModeZeroOrMany = 3

  # Typedef

  typedef :uint, :ForEach
  typedef :uint, :WindowResizeEdge
  typedef :uint, :DrawBrushType
  typedef :uint, :DrawLineCap
  typedef :uint, :DrawLineJoin
  typedef :uint, :DrawFillMode
  typedef :uint, :AttributeType
  typedef :uint, :TextWeight
  typedef :uint, :TextItalic
  typedef :uint, :TextStretch
  typedef :uint, :Underline
  typedef :uint, :UnderlineColor
  callback :uiOpenTypeFeaturesForEachFunc, [:pointer, :char, :char, :char, :char, :uint, :pointer], :uint
  callback :uiAttributedStringForEachAttributeFunc, [:pointer, :pointer, :ulong, :ulong, :pointer], :uint
  typedef :uint, :DrawTextAlign
  typedef :uint, :Modifiers
  typedef :uint, :ExtKey
  typedef :uint, :Align
  typedef :uint, :At
  typedef :uint, :TableValueType
  typedef :uint, :SortIndicator
  typedef :uint, :TableSelectionMode

  # Struct

  class InitOptions < FFI::Struct
    layout(
      :Size, :ulong,
    )
  end

  class Control < FFI::Struct
    layout(
      :Signature, :uint,
      :OSSignature, :uint,
      :TypeSignature, :uint,
      :Destroy, :pointer,
      :Handle, :pointer,
      :Parent, :pointer,
      :SetParent, :pointer,
      :Toplevel, :pointer,
      :Visible, :pointer,
      :Show, :pointer,
      :Hide, :pointer,
      :Enabled, :pointer,
      :Enable, :pointer,
      :Disable, :pointer,
    )
  end

  class AreaHandler < FFI::Struct
    layout(
      :Draw, :pointer,
      :MouseEvent, :pointer,
      :MouseCrossed, :pointer,
      :DragBroken, :pointer,
      :KeyEvent, :pointer,
    )
  end

  class AreaDrawParams < FFI::Struct
    layout(
      :Context, :pointer,
      :AreaWidth, :double,
      :AreaHeight, :double,
      :ClipX, :double,
      :ClipY, :double,
      :ClipWidth, :double,
      :ClipHeight, :double,
    )
  end

  class AreaMouseEvent < FFI::Struct
    layout(
      :X, :double,
      :Y, :double,
      :AreaWidth, :double,
      :AreaHeight, :double,
      :Down, :int,
      :Up, :int,
      :Count, :int,
      :Modifiers, :uint,
      :Held1To64, :ulong_long,
    )
  end

  class AreaKeyEvent < FFI::Struct
    layout(
      :Key, :char,
      :ExtKey, :uint,
      :Modifier, :uint,
      :Modifiers, :uint,
      :Up, :int,
    )
  end

  class DrawBrush < FFI::Struct
    layout(
      :Type, :uint,
      :R, :double,
      :G, :double,
      :B, :double,
      :A, :double,
      :X0, :double,
      :Y0, :double,
      :X1, :double,
      :Y1, :double,
      :OuterRadius, :double,
      :Stops, :pointer,
      :NumStops, :ulong,
    )
  end

  class DrawStrokeParams < FFI::Struct
    layout(
      :Cap, :uint,
      :Join, :uint,
      :Thickness, :double,
      :MiterLimit, :double,
      :Dashes, :pointer,
      :NumDashes, :ulong,
      :DashPhase, :double,
    )
  end

  class DrawMatrix < FFI::Struct
    layout(
      :M11, :double,
      :M12, :double,
      :M21, :double,
      :M22, :double,
      :M31, :double,
      :M32, :double,
    )
  end

  class DrawBrushGradientStop < FFI::Struct
    layout(
      :Pos, :double,
      :R, :double,
      :G, :double,
      :B, :double,
      :A, :double,
    )
  end

  class FontDescriptor < FFI::Struct
    layout(
      :Family, :pointer,
      :Size, :double,
      :Weight, :uint,
      :Italic, :uint,
      :Stretch, :uint,
    )
  end

  class DrawTextLayoutParams < FFI::Struct
    layout(
      :String, :pointer,
      :DefaultFont, :pointer,
      :Width, :double,
      :Align, :uint,
    )
  end

  class TableModelHandler < FFI::Struct
    layout(
      :NumColumns, :pointer,
      :ColumnType, :pointer,
      :NumRows, :pointer,
      :CellValue, :pointer,
      :SetCellValue, :pointer,
    )
  end

  class TableTextColumnOptionalParams < FFI::Struct
    layout(
      :ColorModelColumn, :int,
    )
  end

  class TableParams < FFI::Struct
    layout(
      :Model, :pointer,
      :RowBackgroundColorModelColumn, :int,
    )
  end

  class TableSelection < FFI::Struct
    layout(
      :NumRows, :int,
      :Rows, :pointer,
    )
  end

  # Function

  def self.setup_main_symbols(output_error = false)
    entries = [
      [:uiInit, [:pointer], :pointer],
      [:uiUninit, [], :void],
      [:uiFreeInitError, [:pointer], :void],
      [:uiMain, [], :void],
      [:uiMainSteps, [], :void],
      [:uiMainStep, [:int], :int],
      [:uiQuit, [], :void],
      [:uiQueueMain, [:pointer, :pointer], :void],
      [:uiTimer, [:int, :pointer, :pointer], :void],
      [:uiOnShouldQuit, [:pointer, :pointer], :void],
      [:uiFreeText, [:pointer], :void],
      [:uiControlDestroy, [:pointer], :void],
      [:uiControlHandle, [:pointer], :uintptr_t],
      [:uiControlParent, [:pointer], :pointer],
      [:uiControlSetParent, [:pointer, :pointer], :void],
      [:uiControlToplevel, [:pointer], :int],
      [:uiControlVisible, [:pointer], :int],
      [:uiControlShow, [:pointer], :void],
      [:uiControlHide, [:pointer], :void],
      [:uiControlEnabled, [:pointer], :int],
      [:uiControlEnable, [:pointer], :void],
      [:uiControlDisable, [:pointer], :void],
      [:uiAllocControl, [:ulong, :uint, :uint, :pointer], :pointer],
      [:uiFreeControl, [:pointer], :void],
      [:uiControlVerifySetParent, [:pointer, :pointer], :void],
      [:uiControlEnabledToUser, [:pointer], :int],
      [:uiUserBugCannotSetParentOnToplevel, [:pointer], :void],
      [:uiWindowTitle, [:pointer], :pointer],
      [:uiWindowSetTitle, [:pointer, :pointer], :void],
      [:uiWindowContentSize, [:pointer, :pointer, :pointer], :void],
      [:uiWindowSetContentSize, [:pointer, :int, :int], :void],
      [:uiWindowFullscreen, [:pointer], :int],
      [:uiWindowSetFullscreen, [:pointer, :int], :void],
      [:uiWindowOnContentSizeChanged, [:pointer, :pointer, :pointer], :void],
      [:uiWindowOnClosing, [:pointer, :pointer, :pointer], :void],
      [:uiWindowOnFocusChanged, [:pointer, :pointer, :pointer], :void],
      [:uiWindowFocused, [:pointer], :int],
      [:uiWindowBorderless, [:pointer], :int],
      [:uiWindowSetBorderless, [:pointer, :int], :void],
      [:uiWindowSetChild, [:pointer, :pointer], :void],
      [:uiWindowMargined, [:pointer], :int],
      [:uiWindowSetMargined, [:pointer, :int], :void],
      [:uiWindowResizeable, [:pointer], :int],
      [:uiWindowSetResizeable, [:pointer, :int], :void],
      [:uiNewWindow, [:pointer, :int, :int, :int], :pointer],
      [:uiButtonText, [:pointer], :pointer],
      [:uiButtonSetText, [:pointer, :pointer], :void],
      [:uiButtonOnClicked, [:pointer, :pointer, :pointer], :void],
      [:uiNewButton, [:pointer], :pointer],
      [:uiBoxAppend, [:pointer, :pointer, :int], :void],
      [:uiBoxNumChildren, [:pointer], :int],
      [:uiBoxDelete, [:pointer, :int], :void],
      [:uiBoxPadded, [:pointer], :int],
      [:uiBoxSetPadded, [:pointer, :int], :void],
      [:uiNewHorizontalBox, [], :pointer],
      [:uiNewVerticalBox, [], :pointer],
      [:uiCheckboxText, [:pointer], :pointer],
      [:uiCheckboxSetText, [:pointer, :pointer], :void],
      [:uiCheckboxOnToggled, [:pointer, :pointer, :pointer], :void],
      [:uiCheckboxChecked, [:pointer], :int],
      [:uiCheckboxSetChecked, [:pointer, :int], :void],
      [:uiNewCheckbox, [:pointer], :pointer],
      [:uiEntryText, [:pointer], :pointer],
      [:uiEntrySetText, [:pointer, :pointer], :void],
      [:uiEntryOnChanged, [:pointer, :pointer, :pointer], :void],
      [:uiEntryReadOnly, [:pointer], :int],
      [:uiEntrySetReadOnly, [:pointer, :int], :void],
      [:uiNewEntry, [], :pointer],
      [:uiNewPasswordEntry, [], :pointer],
      [:uiNewSearchEntry, [], :pointer],
      [:uiLabelText, [:pointer], :pointer],
      [:uiLabelSetText, [:pointer, :pointer], :void],
      [:uiNewLabel, [:pointer], :pointer],
      [:uiTabAppend, [:pointer, :pointer, :pointer], :void],
      [:uiTabInsertAt, [:pointer, :pointer, :int, :pointer], :void],
      [:uiTabDelete, [:pointer, :int], :void],
      [:uiTabNumPages, [:pointer], :int],
      [:uiTabMargined, [:pointer, :int], :int],
      [:uiTabSetMargined, [:pointer, :int, :int], :void],
      [:uiNewTab, [], :pointer],
      [:uiGroupTitle, [:pointer], :pointer],
      [:uiGroupSetTitle, [:pointer, :pointer], :void],
      [:uiGroupSetChild, [:pointer, :pointer], :void],
      [:uiGroupMargined, [:pointer], :int],
      [:uiGroupSetMargined, [:pointer, :int], :void],
      [:uiNewGroup, [:pointer], :pointer],
      [:uiSpinboxValue, [:pointer], :int],
      [:uiSpinboxSetValue, [:pointer, :int], :void],
      [:uiSpinboxOnChanged, [:pointer, :pointer, :pointer], :void],
      [:uiNewSpinbox, [:int, :int], :pointer],
      [:uiSliderValue, [:pointer], :int],
      [:uiSliderSetValue, [:pointer, :int], :void],
      [:uiSliderHasToolTip, [:pointer], :int],
      [:uiSliderSetHasToolTip, [:pointer, :int], :void],
      [:uiSliderOnChanged, [:pointer, :pointer, :pointer], :void],
      [:uiSliderOnReleased, [:pointer, :pointer, :pointer], :void],
      [:uiSliderSetRange, [:pointer, :int, :int], :void],
      [:uiNewSlider, [:int, :int], :pointer],
      [:uiProgressBarValue, [:pointer], :int],
      [:uiProgressBarSetValue, [:pointer, :int], :void],
      [:uiNewProgressBar, [], :pointer],
      [:uiNewHorizontalSeparator, [], :pointer],
      [:uiNewVerticalSeparator, [], :pointer],
      [:uiComboboxAppend, [:pointer, :pointer], :void],
      [:uiComboboxInsertAt, [:pointer, :int, :pointer], :void],
      [:uiComboboxDelete, [:pointer, :int], :void],
      [:uiComboboxClear, [:pointer], :void],
      [:uiComboboxNumItems, [:pointer], :int],
      [:uiComboboxSelected, [:pointer], :int],
      [:uiComboboxSetSelected, [:pointer, :int], :void],
      [:uiComboboxOnSelected, [:pointer, :pointer, :pointer], :void],
      [:uiNewCombobox, [], :pointer],
      [:uiEditableComboboxAppend, [:pointer, :pointer], :void],
      [:uiEditableComboboxText, [:pointer], :pointer],
      [:uiEditableComboboxSetText, [:pointer, :pointer], :void],
      [:uiEditableComboboxOnChanged, [:pointer, :pointer, :pointer], :void],
      [:uiNewEditableCombobox, [], :pointer],
      [:uiRadioButtonsAppend, [:pointer, :pointer], :void],
      [:uiRadioButtonsSelected, [:pointer], :int],
      [:uiRadioButtonsSetSelected, [:pointer, :int], :void],
      [:uiRadioButtonsOnSelected, [:pointer, :pointer, :pointer], :void],
      [:uiNewRadioButtons, [], :pointer],
      [:uiDateTimePickerTime, [:pointer, :pointer], :void],
      [:uiDateTimePickerSetTime, [:pointer, :pointer], :void],
      [:uiDateTimePickerOnChanged, [:pointer, :pointer, :pointer], :void],
      [:uiNewDateTimePicker, [], :pointer],
      [:uiNewDatePicker, [], :pointer],
      [:uiNewTimePicker, [], :pointer],
      [:uiMultilineEntryText, [:pointer], :pointer],
      [:uiMultilineEntrySetText, [:pointer, :pointer], :void],
      [:uiMultilineEntryAppend, [:pointer, :pointer], :void],
      [:uiMultilineEntryOnChanged, [:pointer, :pointer, :pointer], :void],
      [:uiMultilineEntryReadOnly, [:pointer], :int],
      [:uiMultilineEntrySetReadOnly, [:pointer, :int], :void],
      [:uiNewMultilineEntry, [], :pointer],
      [:uiNewNonWrappingMultilineEntry, [], :pointer],
      [:uiMenuItemEnable, [:pointer], :void],
      [:uiMenuItemDisable, [:pointer], :void],
      [:uiMenuItemOnClicked, [:pointer, :pointer, :pointer], :void],
      [:uiMenuItemChecked, [:pointer], :int],
      [:uiMenuItemSetChecked, [:pointer, :int], :void],
      [:uiMenuAppendItem, [:pointer, :pointer], :pointer],
      [:uiMenuAppendCheckItem, [:pointer, :pointer], :pointer],
      [:uiMenuAppendQuitItem, [:pointer], :pointer],
      [:uiMenuAppendPreferencesItem, [:pointer], :pointer],
      [:uiMenuAppendAboutItem, [:pointer], :pointer],
      [:uiMenuAppendSeparator, [:pointer], :void],
      [:uiNewMenu, [:pointer], :pointer],
      [:uiOpenFile, [:pointer], :pointer],
      [:uiOpenFolder, [:pointer], :pointer],
      [:uiSaveFile, [:pointer], :pointer],
      [:uiMsgBox, [:pointer, :pointer, :pointer], :void],
      [:uiMsgBoxError, [:pointer, :pointer, :pointer], :void],
      [:uiAreaSetSize, [:pointer, :int, :int], :void],
      [:uiAreaQueueRedrawAll, [:pointer], :void],
      [:uiAreaScrollTo, [:pointer, :double, :double, :double, :double], :void],
      [:uiAreaBeginUserWindowMove, [:pointer], :void],
      [:uiAreaBeginUserWindowResize, [:pointer, :uint], :void],
      [:uiNewArea, [:pointer], :pointer],
      [:uiNewScrollingArea, [:pointer, :int, :int], :pointer],
      [:uiDrawNewPath, [:uint], :pointer],
      [:uiDrawFreePath, [:pointer], :void],
      [:uiDrawPathNewFigure, [:pointer, :double, :double], :void],
      [:uiDrawPathNewFigureWithArc, [:pointer, :double, :double, :double, :double, :double, :int], :void],
      [:uiDrawPathLineTo, [:pointer, :double, :double], :void],
      [:uiDrawPathArcTo, [:pointer, :double, :double, :double, :double, :double, :int], :void],
      [:uiDrawPathBezierTo, [:pointer, :double, :double, :double, :double, :double, :double], :void],
      [:uiDrawPathCloseFigure, [:pointer], :void],
      [:uiDrawPathAddRectangle, [:pointer, :double, :double, :double, :double], :void],
      [:uiDrawPathEnded, [:pointer], :int],
      [:uiDrawPathEnd, [:pointer], :void],
      [:uiDrawStroke, [:pointer, :pointer, :pointer, :pointer], :void],
      [:uiDrawFill, [:pointer, :pointer, :pointer], :void],
      [:uiDrawMatrixSetIdentity, [:pointer], :void],
      [:uiDrawMatrixTranslate, [:pointer, :double, :double], :void],
      [:uiDrawMatrixScale, [:pointer, :double, :double, :double, :double], :void],
      [:uiDrawMatrixRotate, [:pointer, :double, :double, :double], :void],
      [:uiDrawMatrixSkew, [:pointer, :double, :double, :double, :double], :void],
      [:uiDrawMatrixMultiply, [:pointer, :pointer], :void],
      [:uiDrawMatrixInvertible, [:pointer], :int],
      [:uiDrawMatrixInvert, [:pointer], :int],
      [:uiDrawMatrixTransformPoint, [:pointer, :pointer, :pointer], :void],
      [:uiDrawMatrixTransformSize, [:pointer, :pointer, :pointer], :void],
      [:uiDrawTransform, [:pointer, :pointer], :void],
      [:uiDrawClip, [:pointer, :pointer], :void],
      [:uiDrawSave, [:pointer], :void],
      [:uiDrawRestore, [:pointer], :void],
      [:uiFreeAttribute, [:pointer], :void],
      [:uiAttributeGetType, [:pointer], :uint],
      [:uiNewFamilyAttribute, [:pointer], :pointer],
      [:uiAttributeFamily, [:pointer], :pointer],
      [:uiNewSizeAttribute, [:double], :pointer],
      [:uiAttributeSize, [:pointer], :double],
      [:uiNewWeightAttribute, [:uint], :pointer],
      [:uiAttributeWeight, [:pointer], :uint],
      [:uiNewItalicAttribute, [:uint], :pointer],
      [:uiAttributeItalic, [:pointer], :uint],
      [:uiNewStretchAttribute, [:uint], :pointer],
      [:uiAttributeStretch, [:pointer], :uint],
      [:uiNewColorAttribute, [:double, :double, :double, :double], :pointer],
      [:uiAttributeColor, [:pointer, :pointer, :pointer, :pointer, :pointer], :void],
      [:uiNewBackgroundAttribute, [:double, :double, :double, :double], :pointer],
      [:uiNewUnderlineAttribute, [:uint], :pointer],
      [:uiAttributeUnderline, [:pointer], :uint],
      [:uiNewUnderlineColorAttribute, [:uint, :double, :double, :double, :double], :pointer],
      [:uiAttributeUnderlineColor, [:pointer, :pointer, :pointer, :pointer, :pointer, :pointer], :void],
      [:uiNewOpenTypeFeatures, [], :pointer],
      [:uiFreeOpenTypeFeatures, [:pointer], :void],
      [:uiOpenTypeFeaturesClone, [:pointer], :pointer],
      [:uiOpenTypeFeaturesAdd, [:pointer, :char, :char, :char, :char, :uint], :void],
      [:uiOpenTypeFeaturesRemove, [:pointer, :char, :char, :char, :char], :void],
      [:uiOpenTypeFeaturesGet, [:pointer, :char, :char, :char, :char, :pointer], :int],
      [:uiOpenTypeFeaturesForEach, [:pointer, :uiOpenTypeFeaturesForEachFunc, :pointer], :void],
      [:uiNewFeaturesAttribute, [:pointer], :pointer],
      [:uiAttributeFeatures, [:pointer], :pointer],
      [:uiNewAttributedString, [:pointer], :pointer],
      [:uiFreeAttributedString, [:pointer], :void],
      [:uiAttributedStringString, [:pointer], :pointer],
      [:uiAttributedStringLen, [:pointer], :size_t],
      [:uiAttributedStringAppendUnattributed, [:pointer, :pointer], :void],
      [:uiAttributedStringInsertAtUnattributed, [:pointer, :pointer, :ulong], :void],
      [:uiAttributedStringDelete, [:pointer, :ulong, :ulong], :void],
      [:uiAttributedStringSetAttribute, [:pointer, :pointer, :ulong, :ulong], :void],
      [:uiAttributedStringForEachAttribute, [:pointer, :uiAttributedStringForEachAttributeFunc, :pointer], :void],
      [:uiAttributedStringNumGraphemes, [:pointer], :size_t],
      [:uiAttributedStringByteIndexToGrapheme, [:pointer, :ulong], :size_t],
      [:uiAttributedStringGraphemeToByteIndex, [:pointer, :ulong], :size_t],
      [:uiLoadControlFont, [:pointer], :void],
      [:uiFreeFontDescriptor, [:pointer], :void],
      [:uiDrawNewTextLayout, [:pointer], :pointer],
      [:uiDrawFreeTextLayout, [:pointer], :void],
      [:uiDrawText, [:pointer, :pointer, :double, :double], :void],
      [:uiDrawTextLayoutExtents, [:pointer, :pointer, :pointer], :void],
      [:uiFontButtonFont, [:pointer, :pointer], :void],
      [:uiFontButtonOnChanged, [:pointer, :pointer, :pointer], :void],
      [:uiNewFontButton, [], :pointer],
      [:uiFreeFontButtonFont, [:pointer], :void],
      [:uiColorButtonColor, [:pointer, :pointer, :pointer, :pointer, :pointer], :void],
      [:uiColorButtonSetColor, [:pointer, :double, :double, :double, :double], :void],
      [:uiColorButtonOnChanged, [:pointer, :pointer, :pointer], :void],
      [:uiNewColorButton, [], :pointer],
      [:uiFormAppend, [:pointer, :pointer, :pointer, :int], :void],
      [:uiFormNumChildren, [:pointer], :int],
      [:uiFormDelete, [:pointer, :int], :void],
      [:uiFormPadded, [:pointer], :int],
      [:uiFormSetPadded, [:pointer, :int], :void],
      [:uiNewForm, [], :pointer],
      [:uiGridAppend, [:pointer, :pointer, :int, :int, :int, :int, :int, :uint, :int, :uint], :void],
      [:uiGridInsertAt, [:pointer, :pointer, :pointer, :uint, :int, :int, :int, :uint, :int, :uint], :void],
      [:uiGridPadded, [:pointer], :int],
      [:uiGridSetPadded, [:pointer, :int], :void],
      [:uiNewGrid, [], :pointer],
      [:uiNewImage, [:double, :double], :pointer],
      [:uiFreeImage, [:pointer], :void],
      [:uiImageAppend, [:pointer, :pointer, :int, :int, :int], :void],
      [:uiFreeTableValue, [:pointer], :void],
      [:uiTableValueGetType, [:pointer], :uint],
      [:uiNewTableValueString, [:pointer], :pointer],
      [:uiTableValueString, [:pointer], :pointer],
      [:uiNewTableValueImage, [:pointer], :pointer],
      [:uiTableValueImage, [:pointer], :pointer],
      [:uiNewTableValueInt, [:int], :pointer],
      [:uiTableValueInt, [:pointer], :int],
      [:uiNewTableValueColor, [:double, :double, :double, :double], :pointer],
      [:uiTableValueColor, [:pointer, :pointer, :pointer, :pointer, :pointer], :void],
      [:uiNewTableModel, [:pointer], :pointer],
      [:uiFreeTableModel, [:pointer], :void],
      [:uiTableModelRowInserted, [:pointer, :int], :void],
      [:uiTableModelRowChanged, [:pointer, :int], :void],
      [:uiTableModelRowDeleted, [:pointer, :int], :void],
      [:uiTableAppendTextColumn, [:pointer, :pointer, :int, :int, :pointer], :void],
      [:uiTableAppendImageColumn, [:pointer, :pointer, :int], :void],
      [:uiTableAppendImageTextColumn, [:pointer, :pointer, :int, :int, :int, :pointer], :void],
      [:uiTableAppendCheckboxColumn, [:pointer, :pointer, :int, :int], :void],
      [:uiTableAppendCheckboxTextColumn, [:pointer, :pointer, :int, :int, :int, :int, :pointer], :void],
      [:uiTableAppendProgressBarColumn, [:pointer, :pointer, :int], :void],
      [:uiTableAppendButtonColumn, [:pointer, :pointer, :int, :int], :void],
      [:uiTableHeaderVisible, [:pointer], :int],
      [:uiTableHeaderSetVisible, [:pointer, :int], :void],
      [:uiNewTable, [:pointer], :pointer],
      [:uiTableOnRowClicked, [:pointer, :pointer, :pointer], :void],
      [:uiTableOnRowDoubleClicked, [:pointer, :pointer, :pointer], :void],
      [:uiTableHeaderSetSortIndicator, [:pointer, :int, :uint], :void],
      [:uiTableHeaderSortIndicator, [:pointer, :int], :uint],
      [:uiTableHeaderOnClicked, [:pointer, :pointer, :pointer], :void],
      [:uiTableColumnWidth, [:pointer, :int], :int],
      [:uiTableColumnSetWidth, [:pointer, :int, :int], :void],
      [:uiTableGetSelectionMode, [:pointer], :uint],
      [:uiTableSetSelectionMode, [:pointer, :uint], :void],
      [:uiTableOnSelectionChanged, [:pointer, :pointer, :pointer], :void],
      [:uiTableGetSelection, [:pointer], :pointer],
      [:uiTableSetSelection, [:pointer, :pointer], :void],
      [:uiFreeTableSelection, [:pointer], :void],
    ]
    entries.each do |entry|
      begin
        attach_function entry[0].to_s[2..], entry[0], entry[1], entry[2] # [2..] to omit first 2 characters ('ui')
      rescue FFI::NotFoundError => error
        $stderr.puts("[Warning] Failed to import #{entry[0]} (#{error}).") if output_error
      end
    end
  end

end

