# Yet another libui-ng wrapper for Ruby
#
# * https://github.com/vaiorabbit/libuing-bindings
#
# [NOTICE] Autogenerated. Do not edit.

require 'ffi'

module UI
  extend FFI::Library
  # Define/Macro

  Pi = 3.14159265358979323846264338327950288419716939937510582097494459
  DrawDefaultMiterLimit = 10.0
  TableModelColumnNeverEditable = -1
  TableModelColumnAlwaysEditable = -2

  # Enum

  ForEachContinue = 0
  ForEachStop = 1
  WindowResizeEdgeLeft = 0
  WindowResizeEdgeTop = 1
  WindowResizeEdgeRight = 2
  WindowResizeEdgeBottom = 3
  WindowResizeEdgeTopLeft = 4
  WindowResizeEdgeTopRight = 5
  WindowResizeEdgeBottomLeft = 6
  WindowResizeEdgeBottomRight = 7
  DrawBrushTypeSolid = 0
  DrawBrushTypeLinearGradient = 1
  DrawBrushTypeRadialGradient = 2
  DrawBrushTypeImage = 3
  DrawLineCapFlat = 0
  DrawLineCapRound = 1
  DrawLineCapSquare = 2
  DrawLineJoinMiter = 0
  DrawLineJoinRound = 1
  DrawLineJoinBevel = 2
  DrawFillModeWinding = 0
  DrawFillModeAlternate = 1
  AttributeTypeFamily = 0
  AttributeTypeSize = 1
  AttributeTypeWeight = 2
  AttributeTypeItalic = 3
  AttributeTypeStretch = 4
  AttributeTypeColor = 5
  AttributeTypeBackground = 6
  AttributeTypeUnderline = 7
  AttributeTypeUnderlineColor = 8
  AttributeTypeFeatures = 9
  TextWeightMinimum = 0
  TextWeightThin = 100
  TextWeightUltraLight = 200
  TextWeightLight = 300
  TextWeightBook = 350
  TextWeightNormal = 400
  TextWeightMedium = 500
  TextWeightSemiBold = 600
  TextWeightBold = 700
  TextWeightUltraBold = 800
  TextWeightHeavy = 900
  TextWeightUltraHeavy = 950
  TextWeightMaximum = 1000
  TextItalicNormal = 0
  TextItalicOblique = 1
  TextItalicItalic = 2
  TextStretchUltraCondensed = 0
  TextStretchExtraCondensed = 1
  TextStretchCondensed = 2
  TextStretchSemiCondensed = 3
  TextStretchNormal = 4
  TextStretchSemiExpanded = 5
  TextStretchExpanded = 6
  TextStretchExtraExpanded = 7
  TextStretchUltraExpanded = 8
  UnderlineNone = 0
  UnderlineSingle = 1
  UnderlineDouble = 2
  UnderlineSuggestion = 3
  UnderlineColorCustom = 0
  UnderlineColorSpelling = 1
  UnderlineColorGrammar = 2
  UnderlineColorAuxiliary = 3
  DrawTextAlignLeft = 0
  DrawTextAlignCenter = 1
  DrawTextAlignRight = 2
  ModifierCtrl = 1
  ModifierAlt = 2
  ModifierShift = 4
  ModifierSuper = 8
  ExtKeyEscape = 1
  ExtKeyInsert = 2
  ExtKeyDelete = 3
  ExtKeyHome = 4
  ExtKeyEnd = 5
  ExtKeyPageUp = 6
  ExtKeyPageDown = 7
  ExtKeyUp = 8
  ExtKeyDown = 9
  ExtKeyLeft = 10
  ExtKeyRight = 11
  ExtKeyF1 = 12
  ExtKeyF2 = 13
  ExtKeyF3 = 14
  ExtKeyF4 = 15
  ExtKeyF5 = 16
  ExtKeyF6 = 17
  ExtKeyF7 = 18
  ExtKeyF8 = 19
  ExtKeyF9 = 20
  ExtKeyF10 = 21
  ExtKeyF11 = 22
  ExtKeyF12 = 23
  ExtKeyN0 = 24
  ExtKeyN1 = 25
  ExtKeyN2 = 26
  ExtKeyN3 = 27
  ExtKeyN4 = 28
  ExtKeyN5 = 29
  ExtKeyN6 = 30
  ExtKeyN7 = 31
  ExtKeyN8 = 32
  ExtKeyN9 = 33
  ExtKeyNDot = 34
  ExtKeyNEnter = 35
  ExtKeyNAdd = 36
  ExtKeyNSubtract = 37
  ExtKeyNMultiply = 38
  ExtKeyNDivide = 39
  AlignFill = 0
  AlignStart = 1
  AlignCenter = 2
  AlignEnd = 3
  AtLeading = 0
  AtTop = 1
  AtTrailing = 2
  AtBottom = 3
  TableValueTypeString = 0
  TableValueTypeImage = 1
  TableValueTypeInt = 2
  TableValueTypeColor = 3
  SortIndicatorNone = 0
  SortIndicatorAscending = 1
  SortIndicatorDescending = 2
  TableSelectionModeNone = 0
  TableSelectionModeZeroOrOne = 1
  TableSelectionModeOne = 2
  TableSelectionModeZeroOrMany = 3

  # Typedef

  typedef :uint, :ForEach
  typedef :uint, :WindowResizeEdge
  typedef :uint, :DrawBrushType
  typedef :uint, :DrawLineCap
  typedef :uint, :DrawLineJoin
  typedef :uint, :DrawFillMode
  typedef :uint, :AttributeType
  typedef :uint, :TextWeight
  typedef :uint, :TextItalic
  typedef :uint, :TextStretch
  typedef :uint, :Underline
  typedef :uint, :UnderlineColor
  callback :uiOpenTypeFeaturesForEachFunc, [:pointer, :char, :char, :char, :char, :uint, :pointer], :uint
  callback :uiAttributedStringForEachAttributeFunc, [:pointer, :pointer, :ulong, :ulong, :pointer], :uint
  typedef :uint, :DrawTextAlign
  typedef :uint, :Modifiers
  typedef :uint, :ExtKey
  typedef :uint, :Align
  typedef :uint, :At
  typedef :uint, :TableValueType
  typedef :uint, :SortIndicator
  typedef :uint, :TableSelectionMode

  # Struct

  class InitOptions < FFI::Struct
    layout(
      :Size, :ulong,
    )
  end

  class Control < FFI::Struct
    layout(
      :Signature, :uint,
      :OSSignature, :uint,
      :TypeSignature, :uint,
      :Destroy, :pointer,
      :Handle, :pointer,
      :Parent, :pointer,
      :SetParent, :pointer,
      :Toplevel, :pointer,
      :Visible, :pointer,
      :Show, :pointer,
      :Hide, :pointer,
      :Enabled, :pointer,
      :Enable, :pointer,
      :Disable, :pointer,
    )
  end

  class AreaHandler < FFI::Struct
    layout(
      :Draw, :pointer,
      :MouseEvent, :pointer,
      :MouseCrossed, :pointer,
      :DragBroken, :pointer,
      :KeyEvent, :pointer,
    )
  end

  class AreaDrawParams < FFI::Struct
    layout(
      :Context, :pointer,
      :AreaWidth, :double,
      :AreaHeight, :double,
      :ClipX, :double,
      :ClipY, :double,
      :ClipWidth, :double,
      :ClipHeight, :double,
    )
  end

  class AreaMouseEvent < FFI::Struct
    layout(
      :X, :double,
      :Y, :double,
      :AreaWidth, :double,
      :AreaHeight, :double,
      :Down, :int,
      :Up, :int,
      :Count, :int,
      :Modifiers, :uint,
      :Held1To64, :ulong_long,
    )
  end

  class AreaKeyEvent < FFI::Struct
    layout(
      :Key, :char,
      :ExtKey, :uint,
      :Modifier, :uint,
      :Modifiers, :uint,
      :Up, :int,
    )
  end

  class DrawBrush < FFI::Struct
    layout(
      :Type, :uint,
      :R, :double,
      :G, :double,
      :B, :double,
      :A, :double,
      :X0, :double,
      :Y0, :double,
      :X1, :double,
      :Y1, :double,
      :OuterRadius, :double,
      :Stops, :pointer,
      :NumStops, :ulong,
    )
  end

  class DrawStrokeParams < FFI::Struct
    layout(
      :Cap, :uint,
      :Join, :uint,
      :Thickness, :double,
      :MiterLimit, :double,
      :Dashes, :pointer,
      :NumDashes, :ulong,
      :DashPhase, :double,
    )
  end

  class DrawMatrix < FFI::Struct
    layout(
      :M11, :double,
      :M12, :double,
      :M21, :double,
      :M22, :double,
      :M31, :double,
      :M32, :double,
    )
  end

  class DrawBrushGradientStop < FFI::Struct
    layout(
      :Pos, :double,
      :R, :double,
      :G, :double,
      :B, :double,
      :A, :double,
    )
  end

  class FontDescriptor < FFI::Struct
    layout(
      :Family, :pointer,
      :Size, :double,
      :Weight, :uint,
      :Italic, :uint,
      :Stretch, :uint,
    )
  end

  class DrawTextLayoutParams < FFI::Struct
    layout(
      :String, :pointer,
      :DefaultFont, :pointer,
      :Width, :double,
      :Align, :uint,
    )
  end

  class TableModelHandler < FFI::Struct
    layout(
      :NumColumns, :pointer,
      :ColumnType, :pointer,
      :NumRows, :pointer,
      :CellValue, :pointer,
      :SetCellValue, :pointer,
    )
  end

  class TableTextColumnOptionalParams < FFI::Struct
    layout(
      :ColorModelColumn, :int,
    )
  end

  class TableParams < FFI::Struct
    layout(
      :Model, :pointer,
      :RowBackgroundColorModelColumn, :int,
    )
  end

  class TableSelection < FFI::Struct
    layout(
      :NumRows, :int,
      :Rows, :pointer,
    )
  end


  # Function

  def self.setup_main_symbols(output_error = false)
    symbols = [
      :uiInit,
      :uiUninit,
      :uiFreeInitError,
      :uiMain,
      :uiMainSteps,
      :uiMainStep,
      :uiQuit,
      :uiQueueMain,
      :uiTimer,
      :uiOnShouldQuit,
      :uiFreeText,
      :uiControlDestroy,
      :uiControlHandle,
      :uiControlParent,
      :uiControlSetParent,
      :uiControlToplevel,
      :uiControlVisible,
      :uiControlShow,
      :uiControlHide,
      :uiControlEnabled,
      :uiControlEnable,
      :uiControlDisable,
      :uiAllocControl,
      :uiFreeControl,
      :uiControlVerifySetParent,
      :uiControlEnabledToUser,
      :uiUserBugCannotSetParentOnToplevel,
      :uiWindowTitle,
      :uiWindowSetTitle,
      :uiWindowContentSize,
      :uiWindowSetContentSize,
      :uiWindowFullscreen,
      :uiWindowSetFullscreen,
      :uiWindowOnContentSizeChanged,
      :uiWindowOnClosing,
      :uiWindowOnFocusChanged,
      :uiWindowFocused,
      :uiWindowBorderless,
      :uiWindowSetBorderless,
      :uiWindowSetChild,
      :uiWindowMargined,
      :uiWindowSetMargined,
      :uiWindowResizeable,
      :uiWindowSetResizeable,
      :uiNewWindow,
      :uiButtonText,
      :uiButtonSetText,
      :uiButtonOnClicked,
      :uiNewButton,
      :uiBoxAppend,
      :uiBoxNumChildren,
      :uiBoxDelete,
      :uiBoxPadded,
      :uiBoxSetPadded,
      :uiNewHorizontalBox,
      :uiNewVerticalBox,
      :uiCheckboxText,
      :uiCheckboxSetText,
      :uiCheckboxOnToggled,
      :uiCheckboxChecked,
      :uiCheckboxSetChecked,
      :uiNewCheckbox,
      :uiEntryText,
      :uiEntrySetText,
      :uiEntryOnChanged,
      :uiEntryReadOnly,
      :uiEntrySetReadOnly,
      :uiNewEntry,
      :uiNewPasswordEntry,
      :uiNewSearchEntry,
      :uiLabelText,
      :uiLabelSetText,
      :uiNewLabel,
      :uiTabAppend,
      :uiTabInsertAt,
      :uiTabDelete,
      :uiTabNumPages,
      :uiTabMargined,
      :uiTabSetMargined,
      :uiNewTab,
      :uiGroupTitle,
      :uiGroupSetTitle,
      :uiGroupSetChild,
      :uiGroupMargined,
      :uiGroupSetMargined,
      :uiNewGroup,
      :uiSpinboxValue,
      :uiSpinboxSetValue,
      :uiSpinboxOnChanged,
      :uiNewSpinbox,
      :uiSliderValue,
      :uiSliderSetValue,
      :uiSliderHasToolTip,
      :uiSliderSetHasToolTip,
      :uiSliderOnChanged,
      :uiSliderOnReleased,
      :uiSliderSetRange,
      :uiNewSlider,
      :uiProgressBarValue,
      :uiProgressBarSetValue,
      :uiNewProgressBar,
      :uiNewHorizontalSeparator,
      :uiNewVerticalSeparator,
      :uiComboboxAppend,
      :uiComboboxInsertAt,
      :uiComboboxDelete,
      :uiComboboxClear,
      :uiComboboxNumItems,
      :uiComboboxSelected,
      :uiComboboxSetSelected,
      :uiComboboxOnSelected,
      :uiNewCombobox,
      :uiEditableComboboxAppend,
      :uiEditableComboboxText,
      :uiEditableComboboxSetText,
      :uiEditableComboboxOnChanged,
      :uiNewEditableCombobox,
      :uiRadioButtonsAppend,
      :uiRadioButtonsSelected,
      :uiRadioButtonsSetSelected,
      :uiRadioButtonsOnSelected,
      :uiNewRadioButtons,
      :uiDateTimePickerTime,
      :uiDateTimePickerSetTime,
      :uiDateTimePickerOnChanged,
      :uiNewDateTimePicker,
      :uiNewDatePicker,
      :uiNewTimePicker,
      :uiMultilineEntryText,
      :uiMultilineEntrySetText,
      :uiMultilineEntryAppend,
      :uiMultilineEntryOnChanged,
      :uiMultilineEntryReadOnly,
      :uiMultilineEntrySetReadOnly,
      :uiNewMultilineEntry,
      :uiNewNonWrappingMultilineEntry,
      :uiMenuItemEnable,
      :uiMenuItemDisable,
      :uiMenuItemOnClicked,
      :uiMenuItemChecked,
      :uiMenuItemSetChecked,
      :uiMenuAppendItem,
      :uiMenuAppendCheckItem,
      :uiMenuAppendQuitItem,
      :uiMenuAppendPreferencesItem,
      :uiMenuAppendAboutItem,
      :uiMenuAppendSeparator,
      :uiNewMenu,
      :uiOpenFile,
      :uiOpenFolder,
      :uiSaveFile,
      :uiMsgBox,
      :uiMsgBoxError,
      :uiAreaSetSize,
      :uiAreaQueueRedrawAll,
      :uiAreaScrollTo,
      :uiAreaBeginUserWindowMove,
      :uiAreaBeginUserWindowResize,
      :uiNewArea,
      :uiNewScrollingArea,
      :uiDrawNewPath,
      :uiDrawFreePath,
      :uiDrawPathNewFigure,
      :uiDrawPathNewFigureWithArc,
      :uiDrawPathLineTo,
      :uiDrawPathArcTo,
      :uiDrawPathBezierTo,
      :uiDrawPathCloseFigure,
      :uiDrawPathAddRectangle,
      :uiDrawPathEnded,
      :uiDrawPathEnd,
      :uiDrawStroke,
      :uiDrawFill,
      :uiDrawMatrixSetIdentity,
      :uiDrawMatrixTranslate,
      :uiDrawMatrixScale,
      :uiDrawMatrixRotate,
      :uiDrawMatrixSkew,
      :uiDrawMatrixMultiply,
      :uiDrawMatrixInvertible,
      :uiDrawMatrixInvert,
      :uiDrawMatrixTransformPoint,
      :uiDrawMatrixTransformSize,
      :uiDrawTransform,
      :uiDrawClip,
      :uiDrawSave,
      :uiDrawRestore,
      :uiFreeAttribute,
      :uiAttributeGetType,
      :uiNewFamilyAttribute,
      :uiAttributeFamily,
      :uiNewSizeAttribute,
      :uiAttributeSize,
      :uiNewWeightAttribute,
      :uiAttributeWeight,
      :uiNewItalicAttribute,
      :uiAttributeItalic,
      :uiNewStretchAttribute,
      :uiAttributeStretch,
      :uiNewColorAttribute,
      :uiAttributeColor,
      :uiNewBackgroundAttribute,
      :uiNewUnderlineAttribute,
      :uiAttributeUnderline,
      :uiNewUnderlineColorAttribute,
      :uiAttributeUnderlineColor,
      :uiNewOpenTypeFeatures,
      :uiFreeOpenTypeFeatures,
      :uiOpenTypeFeaturesClone,
      :uiOpenTypeFeaturesAdd,
      :uiOpenTypeFeaturesRemove,
      :uiOpenTypeFeaturesGet,
      :uiOpenTypeFeaturesForEach,
      :uiNewFeaturesAttribute,
      :uiAttributeFeatures,
      :uiNewAttributedString,
      :uiFreeAttributedString,
      :uiAttributedStringString,
      :uiAttributedStringLen,
      :uiAttributedStringAppendUnattributed,
      :uiAttributedStringInsertAtUnattributed,
      :uiAttributedStringDelete,
      :uiAttributedStringSetAttribute,
      :uiAttributedStringForEachAttribute,
      :uiAttributedStringNumGraphemes,
      :uiAttributedStringByteIndexToGrapheme,
      :uiAttributedStringGraphemeToByteIndex,
      :uiLoadControlFont,
      :uiFreeFontDescriptor,
      :uiDrawNewTextLayout,
      :uiDrawFreeTextLayout,
      :uiDrawText,
      :uiDrawTextLayoutExtents,
      :uiFontButtonFont,
      :uiFontButtonOnChanged,
      :uiNewFontButton,
      :uiFreeFontButtonFont,
      :uiColorButtonColor,
      :uiColorButtonSetColor,
      :uiColorButtonOnChanged,
      :uiNewColorButton,
      :uiFormAppend,
      :uiFormNumChildren,
      :uiFormDelete,
      :uiFormPadded,
      :uiFormSetPadded,
      :uiNewForm,
      :uiGridAppend,
      :uiGridInsertAt,
      :uiGridPadded,
      :uiGridSetPadded,
      :uiNewGrid,
      :uiNewImage,
      :uiFreeImage,
      :uiImageAppend,
      :uiFreeTableValue,
      :uiTableValueGetType,
      :uiNewTableValueString,
      :uiTableValueString,
      :uiNewTableValueImage,
      :uiTableValueImage,
      :uiNewTableValueInt,
      :uiTableValueInt,
      :uiNewTableValueColor,
      :uiTableValueColor,
      :uiNewTableModel,
      :uiFreeTableModel,
      :uiTableModelRowInserted,
      :uiTableModelRowChanged,
      :uiTableModelRowDeleted,
      :uiTableAppendTextColumn,
      :uiTableAppendImageColumn,
      :uiTableAppendImageTextColumn,
      :uiTableAppendCheckboxColumn,
      :uiTableAppendCheckboxTextColumn,
      :uiTableAppendProgressBarColumn,
      :uiTableAppendButtonColumn,
      :uiTableHeaderVisible,
      :uiTableHeaderSetVisible,
      :uiNewTable,
      :uiTableOnRowClicked,
      :uiTableOnRowDoubleClicked,
      :uiTableHeaderSetSortIndicator,
      :uiTableHeaderSortIndicator,
      :uiTableHeaderOnClicked,
      :uiTableColumnWidth,
      :uiTableColumnSetWidth,
      :uiTableGetSelectionMode,
      :uiTableSetSelectionMode,
      :uiTableOnSelectionChanged,
      :uiTableGetSelection,
      :uiTableSetSelection,
      :uiFreeTableSelection,
    ]
    args = {
      :uiInit => [:pointer],
      :uiUninit => [],
      :uiFreeInitError => [:pointer],
      :uiMain => [],
      :uiMainSteps => [],
      :uiMainStep => [:int],
      :uiQuit => [],
      :uiQueueMain => [:pointer, :pointer],
      :uiTimer => [:int, :pointer, :pointer],
      :uiOnShouldQuit => [:pointer, :pointer],
      :uiFreeText => [:pointer],
      :uiControlDestroy => [:pointer],
      :uiControlHandle => [:pointer],
      :uiControlParent => [:pointer],
      :uiControlSetParent => [:pointer, :pointer],
      :uiControlToplevel => [:pointer],
      :uiControlVisible => [:pointer],
      :uiControlShow => [:pointer],
      :uiControlHide => [:pointer],
      :uiControlEnabled => [:pointer],
      :uiControlEnable => [:pointer],
      :uiControlDisable => [:pointer],
      :uiAllocControl => [:ulong, :uint, :uint, :pointer],
      :uiFreeControl => [:pointer],
      :uiControlVerifySetParent => [:pointer, :pointer],
      :uiControlEnabledToUser => [:pointer],
      :uiUserBugCannotSetParentOnToplevel => [:pointer],
      :uiWindowTitle => [:pointer],
      :uiWindowSetTitle => [:pointer, :pointer],
      :uiWindowContentSize => [:pointer, :pointer, :pointer],
      :uiWindowSetContentSize => [:pointer, :int, :int],
      :uiWindowFullscreen => [:pointer],
      :uiWindowSetFullscreen => [:pointer, :int],
      :uiWindowOnContentSizeChanged => [:pointer, :pointer, :pointer],
      :uiWindowOnClosing => [:pointer, :pointer, :pointer],
      :uiWindowOnFocusChanged => [:pointer, :pointer, :pointer],
      :uiWindowFocused => [:pointer],
      :uiWindowBorderless => [:pointer],
      :uiWindowSetBorderless => [:pointer, :int],
      :uiWindowSetChild => [:pointer, :pointer],
      :uiWindowMargined => [:pointer],
      :uiWindowSetMargined => [:pointer, :int],
      :uiWindowResizeable => [:pointer],
      :uiWindowSetResizeable => [:pointer, :int],
      :uiNewWindow => [:pointer, :int, :int, :int],
      :uiButtonText => [:pointer],
      :uiButtonSetText => [:pointer, :pointer],
      :uiButtonOnClicked => [:pointer, :pointer, :pointer],
      :uiNewButton => [:pointer],
      :uiBoxAppend => [:pointer, :pointer, :int],
      :uiBoxNumChildren => [:pointer],
      :uiBoxDelete => [:pointer, :int],
      :uiBoxPadded => [:pointer],
      :uiBoxSetPadded => [:pointer, :int],
      :uiNewHorizontalBox => [],
      :uiNewVerticalBox => [],
      :uiCheckboxText => [:pointer],
      :uiCheckboxSetText => [:pointer, :pointer],
      :uiCheckboxOnToggled => [:pointer, :pointer, :pointer],
      :uiCheckboxChecked => [:pointer],
      :uiCheckboxSetChecked => [:pointer, :int],
      :uiNewCheckbox => [:pointer],
      :uiEntryText => [:pointer],
      :uiEntrySetText => [:pointer, :pointer],
      :uiEntryOnChanged => [:pointer, :pointer, :pointer],
      :uiEntryReadOnly => [:pointer],
      :uiEntrySetReadOnly => [:pointer, :int],
      :uiNewEntry => [],
      :uiNewPasswordEntry => [],
      :uiNewSearchEntry => [],
      :uiLabelText => [:pointer],
      :uiLabelSetText => [:pointer, :pointer],
      :uiNewLabel => [:pointer],
      :uiTabAppend => [:pointer, :pointer, :pointer],
      :uiTabInsertAt => [:pointer, :pointer, :int, :pointer],
      :uiTabDelete => [:pointer, :int],
      :uiTabNumPages => [:pointer],
      :uiTabMargined => [:pointer, :int],
      :uiTabSetMargined => [:pointer, :int, :int],
      :uiNewTab => [],
      :uiGroupTitle => [:pointer],
      :uiGroupSetTitle => [:pointer, :pointer],
      :uiGroupSetChild => [:pointer, :pointer],
      :uiGroupMargined => [:pointer],
      :uiGroupSetMargined => [:pointer, :int],
      :uiNewGroup => [:pointer],
      :uiSpinboxValue => [:pointer],
      :uiSpinboxSetValue => [:pointer, :int],
      :uiSpinboxOnChanged => [:pointer, :pointer, :pointer],
      :uiNewSpinbox => [:int, :int],
      :uiSliderValue => [:pointer],
      :uiSliderSetValue => [:pointer, :int],
      :uiSliderHasToolTip => [:pointer],
      :uiSliderSetHasToolTip => [:pointer, :int],
      :uiSliderOnChanged => [:pointer, :pointer, :pointer],
      :uiSliderOnReleased => [:pointer, :pointer, :pointer],
      :uiSliderSetRange => [:pointer, :int, :int],
      :uiNewSlider => [:int, :int],
      :uiProgressBarValue => [:pointer],
      :uiProgressBarSetValue => [:pointer, :int],
      :uiNewProgressBar => [],
      :uiNewHorizontalSeparator => [],
      :uiNewVerticalSeparator => [],
      :uiComboboxAppend => [:pointer, :pointer],
      :uiComboboxInsertAt => [:pointer, :int, :pointer],
      :uiComboboxDelete => [:pointer, :int],
      :uiComboboxClear => [:pointer],
      :uiComboboxNumItems => [:pointer],
      :uiComboboxSelected => [:pointer],
      :uiComboboxSetSelected => [:pointer, :int],
      :uiComboboxOnSelected => [:pointer, :pointer, :pointer],
      :uiNewCombobox => [],
      :uiEditableComboboxAppend => [:pointer, :pointer],
      :uiEditableComboboxText => [:pointer],
      :uiEditableComboboxSetText => [:pointer, :pointer],
      :uiEditableComboboxOnChanged => [:pointer, :pointer, :pointer],
      :uiNewEditableCombobox => [],
      :uiRadioButtonsAppend => [:pointer, :pointer],
      :uiRadioButtonsSelected => [:pointer],
      :uiRadioButtonsSetSelected => [:pointer, :int],
      :uiRadioButtonsOnSelected => [:pointer, :pointer, :pointer],
      :uiNewRadioButtons => [],
      :uiDateTimePickerTime => [:pointer, :pointer],
      :uiDateTimePickerSetTime => [:pointer, :pointer],
      :uiDateTimePickerOnChanged => [:pointer, :pointer, :pointer],
      :uiNewDateTimePicker => [],
      :uiNewDatePicker => [],
      :uiNewTimePicker => [],
      :uiMultilineEntryText => [:pointer],
      :uiMultilineEntrySetText => [:pointer, :pointer],
      :uiMultilineEntryAppend => [:pointer, :pointer],
      :uiMultilineEntryOnChanged => [:pointer, :pointer, :pointer],
      :uiMultilineEntryReadOnly => [:pointer],
      :uiMultilineEntrySetReadOnly => [:pointer, :int],
      :uiNewMultilineEntry => [],
      :uiNewNonWrappingMultilineEntry => [],
      :uiMenuItemEnable => [:pointer],
      :uiMenuItemDisable => [:pointer],
      :uiMenuItemOnClicked => [:pointer, :pointer, :pointer],
      :uiMenuItemChecked => [:pointer],
      :uiMenuItemSetChecked => [:pointer, :int],
      :uiMenuAppendItem => [:pointer, :pointer],
      :uiMenuAppendCheckItem => [:pointer, :pointer],
      :uiMenuAppendQuitItem => [:pointer],
      :uiMenuAppendPreferencesItem => [:pointer],
      :uiMenuAppendAboutItem => [:pointer],
      :uiMenuAppendSeparator => [:pointer],
      :uiNewMenu => [:pointer],
      :uiOpenFile => [:pointer],
      :uiOpenFolder => [:pointer],
      :uiSaveFile => [:pointer],
      :uiMsgBox => [:pointer, :pointer, :pointer],
      :uiMsgBoxError => [:pointer, :pointer, :pointer],
      :uiAreaSetSize => [:pointer, :int, :int],
      :uiAreaQueueRedrawAll => [:pointer],
      :uiAreaScrollTo => [:pointer, :double, :double, :double, :double],
      :uiAreaBeginUserWindowMove => [:pointer],
      :uiAreaBeginUserWindowResize => [:pointer, :uint],
      :uiNewArea => [:pointer],
      :uiNewScrollingArea => [:pointer, :int, :int],
      :uiDrawNewPath => [:uint],
      :uiDrawFreePath => [:pointer],
      :uiDrawPathNewFigure => [:pointer, :double, :double],
      :uiDrawPathNewFigureWithArc => [:pointer, :double, :double, :double, :double, :double, :int],
      :uiDrawPathLineTo => [:pointer, :double, :double],
      :uiDrawPathArcTo => [:pointer, :double, :double, :double, :double, :double, :int],
      :uiDrawPathBezierTo => [:pointer, :double, :double, :double, :double, :double, :double],
      :uiDrawPathCloseFigure => [:pointer],
      :uiDrawPathAddRectangle => [:pointer, :double, :double, :double, :double],
      :uiDrawPathEnded => [:pointer],
      :uiDrawPathEnd => [:pointer],
      :uiDrawStroke => [:pointer, :pointer, :pointer, :pointer],
      :uiDrawFill => [:pointer, :pointer, :pointer],
      :uiDrawMatrixSetIdentity => [:pointer],
      :uiDrawMatrixTranslate => [:pointer, :double, :double],
      :uiDrawMatrixScale => [:pointer, :double, :double, :double, :double],
      :uiDrawMatrixRotate => [:pointer, :double, :double, :double],
      :uiDrawMatrixSkew => [:pointer, :double, :double, :double, :double],
      :uiDrawMatrixMultiply => [:pointer, :pointer],
      :uiDrawMatrixInvertible => [:pointer],
      :uiDrawMatrixInvert => [:pointer],
      :uiDrawMatrixTransformPoint => [:pointer, :pointer, :pointer],
      :uiDrawMatrixTransformSize => [:pointer, :pointer, :pointer],
      :uiDrawTransform => [:pointer, :pointer],
      :uiDrawClip => [:pointer, :pointer],
      :uiDrawSave => [:pointer],
      :uiDrawRestore => [:pointer],
      :uiFreeAttribute => [:pointer],
      :uiAttributeGetType => [:pointer],
      :uiNewFamilyAttribute => [:pointer],
      :uiAttributeFamily => [:pointer],
      :uiNewSizeAttribute => [:double],
      :uiAttributeSize => [:pointer],
      :uiNewWeightAttribute => [:uint],
      :uiAttributeWeight => [:pointer],
      :uiNewItalicAttribute => [:uint],
      :uiAttributeItalic => [:pointer],
      :uiNewStretchAttribute => [:uint],
      :uiAttributeStretch => [:pointer],
      :uiNewColorAttribute => [:double, :double, :double, :double],
      :uiAttributeColor => [:pointer, :pointer, :pointer, :pointer, :pointer],
      :uiNewBackgroundAttribute => [:double, :double, :double, :double],
      :uiNewUnderlineAttribute => [:uint],
      :uiAttributeUnderline => [:pointer],
      :uiNewUnderlineColorAttribute => [:uint, :double, :double, :double, :double],
      :uiAttributeUnderlineColor => [:pointer, :pointer, :pointer, :pointer, :pointer, :pointer],
      :uiNewOpenTypeFeatures => [],
      :uiFreeOpenTypeFeatures => [:pointer],
      :uiOpenTypeFeaturesClone => [:pointer],
      :uiOpenTypeFeaturesAdd => [:pointer, :char, :char, :char, :char, :uint],
      :uiOpenTypeFeaturesRemove => [:pointer, :char, :char, :char, :char],
      :uiOpenTypeFeaturesGet => [:pointer, :char, :char, :char, :char, :pointer],
      :uiOpenTypeFeaturesForEach => [:pointer, :uiOpenTypeFeaturesForEachFunc, :pointer],
      :uiNewFeaturesAttribute => [:pointer],
      :uiAttributeFeatures => [:pointer],
      :uiNewAttributedString => [:pointer],
      :uiFreeAttributedString => [:pointer],
      :uiAttributedStringString => [:pointer],
      :uiAttributedStringLen => [:pointer],
      :uiAttributedStringAppendUnattributed => [:pointer, :pointer],
      :uiAttributedStringInsertAtUnattributed => [:pointer, :pointer, :ulong],
      :uiAttributedStringDelete => [:pointer, :ulong, :ulong],
      :uiAttributedStringSetAttribute => [:pointer, :pointer, :ulong, :ulong],
      :uiAttributedStringForEachAttribute => [:pointer, :uiAttributedStringForEachAttributeFunc, :pointer],
      :uiAttributedStringNumGraphemes => [:pointer],
      :uiAttributedStringByteIndexToGrapheme => [:pointer, :ulong],
      :uiAttributedStringGraphemeToByteIndex => [:pointer, :ulong],
      :uiLoadControlFont => [:pointer],
      :uiFreeFontDescriptor => [:pointer],
      :uiDrawNewTextLayout => [:pointer],
      :uiDrawFreeTextLayout => [:pointer],
      :uiDrawText => [:pointer, :pointer, :double, :double],
      :uiDrawTextLayoutExtents => [:pointer, :pointer, :pointer],
      :uiFontButtonFont => [:pointer, :pointer],
      :uiFontButtonOnChanged => [:pointer, :pointer, :pointer],
      :uiNewFontButton => [],
      :uiFreeFontButtonFont => [:pointer],
      :uiColorButtonColor => [:pointer, :pointer, :pointer, :pointer, :pointer],
      :uiColorButtonSetColor => [:pointer, :double, :double, :double, :double],
      :uiColorButtonOnChanged => [:pointer, :pointer, :pointer],
      :uiNewColorButton => [],
      :uiFormAppend => [:pointer, :pointer, :pointer, :int],
      :uiFormNumChildren => [:pointer],
      :uiFormDelete => [:pointer, :int],
      :uiFormPadded => [:pointer],
      :uiFormSetPadded => [:pointer, :int],
      :uiNewForm => [],
      :uiGridAppend => [:pointer, :pointer, :int, :int, :int, :int, :int, :uint, :int, :uint],
      :uiGridInsertAt => [:pointer, :pointer, :pointer, :uint, :int, :int, :int, :uint, :int, :uint],
      :uiGridPadded => [:pointer],
      :uiGridSetPadded => [:pointer, :int],
      :uiNewGrid => [],
      :uiNewImage => [:double, :double],
      :uiFreeImage => [:pointer],
      :uiImageAppend => [:pointer, :pointer, :int, :int, :int],
      :uiFreeTableValue => [:pointer],
      :uiTableValueGetType => [:pointer],
      :uiNewTableValueString => [:pointer],
      :uiTableValueString => [:pointer],
      :uiNewTableValueImage => [:pointer],
      :uiTableValueImage => [:pointer],
      :uiNewTableValueInt => [:int],
      :uiTableValueInt => [:pointer],
      :uiNewTableValueColor => [:double, :double, :double, :double],
      :uiTableValueColor => [:pointer, :pointer, :pointer, :pointer, :pointer],
      :uiNewTableModel => [:pointer],
      :uiFreeTableModel => [:pointer],
      :uiTableModelRowInserted => [:pointer, :int],
      :uiTableModelRowChanged => [:pointer, :int],
      :uiTableModelRowDeleted => [:pointer, :int],
      :uiTableAppendTextColumn => [:pointer, :pointer, :int, :int, :pointer],
      :uiTableAppendImageColumn => [:pointer, :pointer, :int],
      :uiTableAppendImageTextColumn => [:pointer, :pointer, :int, :int, :int, :pointer],
      :uiTableAppendCheckboxColumn => [:pointer, :pointer, :int, :int],
      :uiTableAppendCheckboxTextColumn => [:pointer, :pointer, :int, :int, :int, :int, :pointer],
      :uiTableAppendProgressBarColumn => [:pointer, :pointer, :int],
      :uiTableAppendButtonColumn => [:pointer, :pointer, :int, :int],
      :uiTableHeaderVisible => [:pointer],
      :uiTableHeaderSetVisible => [:pointer, :int],
      :uiNewTable => [:pointer],
      :uiTableOnRowClicked => [:pointer, :pointer, :pointer],
      :uiTableOnRowDoubleClicked => [:pointer, :pointer, :pointer],
      :uiTableHeaderSetSortIndicator => [:pointer, :int, :uint],
      :uiTableHeaderSortIndicator => [:pointer, :int],
      :uiTableHeaderOnClicked => [:pointer, :pointer, :pointer],
      :uiTableColumnWidth => [:pointer, :int],
      :uiTableColumnSetWidth => [:pointer, :int, :int],
      :uiTableGetSelectionMode => [:pointer],
      :uiTableSetSelectionMode => [:pointer, :uint],
      :uiTableOnSelectionChanged => [:pointer, :pointer, :pointer],
      :uiTableGetSelection => [:pointer],
      :uiTableSetSelection => [:pointer, :pointer],
      :uiFreeTableSelection => [:pointer],
    }
    retvals = {
      :uiInit => :pointer,
      :uiUninit => :void,
      :uiFreeInitError => :void,
      :uiMain => :void,
      :uiMainSteps => :void,
      :uiMainStep => :int,
      :uiQuit => :void,
      :uiQueueMain => :void,
      :uiTimer => :void,
      :uiOnShouldQuit => :void,
      :uiFreeText => :void,
      :uiControlDestroy => :void,
      :uiControlHandle => :uintptr_t,
      :uiControlParent => :pointer,
      :uiControlSetParent => :void,
      :uiControlToplevel => :int,
      :uiControlVisible => :int,
      :uiControlShow => :void,
      :uiControlHide => :void,
      :uiControlEnabled => :int,
      :uiControlEnable => :void,
      :uiControlDisable => :void,
      :uiAllocControl => :pointer,
      :uiFreeControl => :void,
      :uiControlVerifySetParent => :void,
      :uiControlEnabledToUser => :int,
      :uiUserBugCannotSetParentOnToplevel => :void,
      :uiWindowTitle => :pointer,
      :uiWindowSetTitle => :void,
      :uiWindowContentSize => :void,
      :uiWindowSetContentSize => :void,
      :uiWindowFullscreen => :int,
      :uiWindowSetFullscreen => :void,
      :uiWindowOnContentSizeChanged => :void,
      :uiWindowOnClosing => :void,
      :uiWindowOnFocusChanged => :void,
      :uiWindowFocused => :int,
      :uiWindowBorderless => :int,
      :uiWindowSetBorderless => :void,
      :uiWindowSetChild => :void,
      :uiWindowMargined => :int,
      :uiWindowSetMargined => :void,
      :uiWindowResizeable => :int,
      :uiWindowSetResizeable => :void,
      :uiNewWindow => :pointer,
      :uiButtonText => :pointer,
      :uiButtonSetText => :void,
      :uiButtonOnClicked => :void,
      :uiNewButton => :pointer,
      :uiBoxAppend => :void,
      :uiBoxNumChildren => :int,
      :uiBoxDelete => :void,
      :uiBoxPadded => :int,
      :uiBoxSetPadded => :void,
      :uiNewHorizontalBox => :pointer,
      :uiNewVerticalBox => :pointer,
      :uiCheckboxText => :pointer,
      :uiCheckboxSetText => :void,
      :uiCheckboxOnToggled => :void,
      :uiCheckboxChecked => :int,
      :uiCheckboxSetChecked => :void,
      :uiNewCheckbox => :pointer,
      :uiEntryText => :pointer,
      :uiEntrySetText => :void,
      :uiEntryOnChanged => :void,
      :uiEntryReadOnly => :int,
      :uiEntrySetReadOnly => :void,
      :uiNewEntry => :pointer,
      :uiNewPasswordEntry => :pointer,
      :uiNewSearchEntry => :pointer,
      :uiLabelText => :pointer,
      :uiLabelSetText => :void,
      :uiNewLabel => :pointer,
      :uiTabAppend => :void,
      :uiTabInsertAt => :void,
      :uiTabDelete => :void,
      :uiTabNumPages => :int,
      :uiTabMargined => :int,
      :uiTabSetMargined => :void,
      :uiNewTab => :pointer,
      :uiGroupTitle => :pointer,
      :uiGroupSetTitle => :void,
      :uiGroupSetChild => :void,
      :uiGroupMargined => :int,
      :uiGroupSetMargined => :void,
      :uiNewGroup => :pointer,
      :uiSpinboxValue => :int,
      :uiSpinboxSetValue => :void,
      :uiSpinboxOnChanged => :void,
      :uiNewSpinbox => :pointer,
      :uiSliderValue => :int,
      :uiSliderSetValue => :void,
      :uiSliderHasToolTip => :int,
      :uiSliderSetHasToolTip => :void,
      :uiSliderOnChanged => :void,
      :uiSliderOnReleased => :void,
      :uiSliderSetRange => :void,
      :uiNewSlider => :pointer,
      :uiProgressBarValue => :int,
      :uiProgressBarSetValue => :void,
      :uiNewProgressBar => :pointer,
      :uiNewHorizontalSeparator => :pointer,
      :uiNewVerticalSeparator => :pointer,
      :uiComboboxAppend => :void,
      :uiComboboxInsertAt => :void,
      :uiComboboxDelete => :void,
      :uiComboboxClear => :void,
      :uiComboboxNumItems => :int,
      :uiComboboxSelected => :int,
      :uiComboboxSetSelected => :void,
      :uiComboboxOnSelected => :void,
      :uiNewCombobox => :pointer,
      :uiEditableComboboxAppend => :void,
      :uiEditableComboboxText => :pointer,
      :uiEditableComboboxSetText => :void,
      :uiEditableComboboxOnChanged => :void,
      :uiNewEditableCombobox => :pointer,
      :uiRadioButtonsAppend => :void,
      :uiRadioButtonsSelected => :int,
      :uiRadioButtonsSetSelected => :void,
      :uiRadioButtonsOnSelected => :void,
      :uiNewRadioButtons => :pointer,
      :uiDateTimePickerTime => :void,
      :uiDateTimePickerSetTime => :void,
      :uiDateTimePickerOnChanged => :void,
      :uiNewDateTimePicker => :pointer,
      :uiNewDatePicker => :pointer,
      :uiNewTimePicker => :pointer,
      :uiMultilineEntryText => :pointer,
      :uiMultilineEntrySetText => :void,
      :uiMultilineEntryAppend => :void,
      :uiMultilineEntryOnChanged => :void,
      :uiMultilineEntryReadOnly => :int,
      :uiMultilineEntrySetReadOnly => :void,
      :uiNewMultilineEntry => :pointer,
      :uiNewNonWrappingMultilineEntry => :pointer,
      :uiMenuItemEnable => :void,
      :uiMenuItemDisable => :void,
      :uiMenuItemOnClicked => :void,
      :uiMenuItemChecked => :int,
      :uiMenuItemSetChecked => :void,
      :uiMenuAppendItem => :pointer,
      :uiMenuAppendCheckItem => :pointer,
      :uiMenuAppendQuitItem => :pointer,
      :uiMenuAppendPreferencesItem => :pointer,
      :uiMenuAppendAboutItem => :pointer,
      :uiMenuAppendSeparator => :void,
      :uiNewMenu => :pointer,
      :uiOpenFile => :pointer,
      :uiOpenFolder => :pointer,
      :uiSaveFile => :pointer,
      :uiMsgBox => :void,
      :uiMsgBoxError => :void,
      :uiAreaSetSize => :void,
      :uiAreaQueueRedrawAll => :void,
      :uiAreaScrollTo => :void,
      :uiAreaBeginUserWindowMove => :void,
      :uiAreaBeginUserWindowResize => :void,
      :uiNewArea => :pointer,
      :uiNewScrollingArea => :pointer,
      :uiDrawNewPath => :pointer,
      :uiDrawFreePath => :void,
      :uiDrawPathNewFigure => :void,
      :uiDrawPathNewFigureWithArc => :void,
      :uiDrawPathLineTo => :void,
      :uiDrawPathArcTo => :void,
      :uiDrawPathBezierTo => :void,
      :uiDrawPathCloseFigure => :void,
      :uiDrawPathAddRectangle => :void,
      :uiDrawPathEnded => :int,
      :uiDrawPathEnd => :void,
      :uiDrawStroke => :void,
      :uiDrawFill => :void,
      :uiDrawMatrixSetIdentity => :void,
      :uiDrawMatrixTranslate => :void,
      :uiDrawMatrixScale => :void,
      :uiDrawMatrixRotate => :void,
      :uiDrawMatrixSkew => :void,
      :uiDrawMatrixMultiply => :void,
      :uiDrawMatrixInvertible => :int,
      :uiDrawMatrixInvert => :int,
      :uiDrawMatrixTransformPoint => :void,
      :uiDrawMatrixTransformSize => :void,
      :uiDrawTransform => :void,
      :uiDrawClip => :void,
      :uiDrawSave => :void,
      :uiDrawRestore => :void,
      :uiFreeAttribute => :void,
      :uiAttributeGetType => :uint,
      :uiNewFamilyAttribute => :pointer,
      :uiAttributeFamily => :pointer,
      :uiNewSizeAttribute => :pointer,
      :uiAttributeSize => :double,
      :uiNewWeightAttribute => :pointer,
      :uiAttributeWeight => :uint,
      :uiNewItalicAttribute => :pointer,
      :uiAttributeItalic => :uint,
      :uiNewStretchAttribute => :pointer,
      :uiAttributeStretch => :uint,
      :uiNewColorAttribute => :pointer,
      :uiAttributeColor => :void,
      :uiNewBackgroundAttribute => :pointer,
      :uiNewUnderlineAttribute => :pointer,
      :uiAttributeUnderline => :uint,
      :uiNewUnderlineColorAttribute => :pointer,
      :uiAttributeUnderlineColor => :void,
      :uiNewOpenTypeFeatures => :pointer,
      :uiFreeOpenTypeFeatures => :void,
      :uiOpenTypeFeaturesClone => :pointer,
      :uiOpenTypeFeaturesAdd => :void,
      :uiOpenTypeFeaturesRemove => :void,
      :uiOpenTypeFeaturesGet => :int,
      :uiOpenTypeFeaturesForEach => :void,
      :uiNewFeaturesAttribute => :pointer,
      :uiAttributeFeatures => :pointer,
      :uiNewAttributedString => :pointer,
      :uiFreeAttributedString => :void,
      :uiAttributedStringString => :pointer,
      :uiAttributedStringLen => :size_t,
      :uiAttributedStringAppendUnattributed => :void,
      :uiAttributedStringInsertAtUnattributed => :void,
      :uiAttributedStringDelete => :void,
      :uiAttributedStringSetAttribute => :void,
      :uiAttributedStringForEachAttribute => :void,
      :uiAttributedStringNumGraphemes => :size_t,
      :uiAttributedStringByteIndexToGrapheme => :size_t,
      :uiAttributedStringGraphemeToByteIndex => :size_t,
      :uiLoadControlFont => :void,
      :uiFreeFontDescriptor => :void,
      :uiDrawNewTextLayout => :pointer,
      :uiDrawFreeTextLayout => :void,
      :uiDrawText => :void,
      :uiDrawTextLayoutExtents => :void,
      :uiFontButtonFont => :void,
      :uiFontButtonOnChanged => :void,
      :uiNewFontButton => :pointer,
      :uiFreeFontButtonFont => :void,
      :uiColorButtonColor => :void,
      :uiColorButtonSetColor => :void,
      :uiColorButtonOnChanged => :void,
      :uiNewColorButton => :pointer,
      :uiFormAppend => :void,
      :uiFormNumChildren => :int,
      :uiFormDelete => :void,
      :uiFormPadded => :int,
      :uiFormSetPadded => :void,
      :uiNewForm => :pointer,
      :uiGridAppend => :void,
      :uiGridInsertAt => :void,
      :uiGridPadded => :int,
      :uiGridSetPadded => :void,
      :uiNewGrid => :pointer,
      :uiNewImage => :pointer,
      :uiFreeImage => :void,
      :uiImageAppend => :void,
      :uiFreeTableValue => :void,
      :uiTableValueGetType => :uint,
      :uiNewTableValueString => :pointer,
      :uiTableValueString => :pointer,
      :uiNewTableValueImage => :pointer,
      :uiTableValueImage => :pointer,
      :uiNewTableValueInt => :pointer,
      :uiTableValueInt => :int,
      :uiNewTableValueColor => :pointer,
      :uiTableValueColor => :void,
      :uiNewTableModel => :pointer,
      :uiFreeTableModel => :void,
      :uiTableModelRowInserted => :void,
      :uiTableModelRowChanged => :void,
      :uiTableModelRowDeleted => :void,
      :uiTableAppendTextColumn => :void,
      :uiTableAppendImageColumn => :void,
      :uiTableAppendImageTextColumn => :void,
      :uiTableAppendCheckboxColumn => :void,
      :uiTableAppendCheckboxTextColumn => :void,
      :uiTableAppendProgressBarColumn => :void,
      :uiTableAppendButtonColumn => :void,
      :uiTableHeaderVisible => :int,
      :uiTableHeaderSetVisible => :void,
      :uiNewTable => :pointer,
      :uiTableOnRowClicked => :void,
      :uiTableOnRowDoubleClicked => :void,
      :uiTableHeaderSetSortIndicator => :void,
      :uiTableHeaderSortIndicator => :uint,
      :uiTableHeaderOnClicked => :void,
      :uiTableColumnWidth => :int,
      :uiTableColumnSetWidth => :void,
      :uiTableGetSelectionMode => :uint,
      :uiTableSetSelectionMode => :void,
      :uiTableOnSelectionChanged => :void,
      :uiTableGetSelection => :pointer,
      :uiTableSetSelection => :void,
      :uiFreeTableSelection => :void,
    }
    symbols.each do |sym|
      begin
        attach_function sym.to_s[2..], sym, args[sym], retvals[sym] # [2..] to omit first 2 characters ('ui')
      rescue FFI::NotFoundError => error
        $stderr.puts("[Warning] Failed to import #{sym} (#{error}).") if output_error
      end
    end
  end

end

